/**
 * 
 */
package com.google.code.joto;

import java.io.File;
import java.io.IOException;
import java.io.PrintStream;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import junit.framework.TestCase;

import com.google.code.joto.customized.EnumeratedTypeProcessor;
import com.google.code.joto.procesors.IgnoreClassProcessor;

/**
 */
public class ReverseEngineerObjectUnitTest
    extends TestCase
{

    /**
     * @see junit.framework.TestCase#setUp()
     */
    protected void setUp()
        throws Exception
    {
        super.setUp();
    }

    /**
     * Test method for
     * {@link lili.generator.ReverseEngineerObject#generateCode(java.lang.Object, java.util.List)}.
     * @throws IOException
     */
    public void testGenerateCode()
        throws IOException
    {
        SomeDummyClass obj = new SomeDummyClass();
        obj.setValues();
        ReverseEngineerObject reverseEngineerObject = new ReverseEngineerObject();

        List<String> someStrings = new ArrayList<String>();
        someStrings.add( "some" );
        someStrings.add( "234" );
        List<CustomProcessor> userSuppliedProcessors = Arrays
            .asList( new EnumeratedTypeProcessor(), IgnoreClassProcessor
                .createForSimpleClassNames( "SomeDataTypeToBeIgnoredOnProcessing" ) );
        final ReverseEngineerObjectResponse response1 = reverseEngineerObject.generateCode( someStrings,
                                                                                            userSuppliedProcessors );
        printAResponse( response1, "SomeStringsSandbox" );

        System.out.println( obj );
        final ReverseEngineerObjectResponse response2 = reverseEngineerObject
            .generateCode( obj, userSuppliedProcessors );
        printAResponse( response2, "SomeDummyClassSandbox" );

        Joto joto = new Joto();
        joto.setDefaultValues();
        final ReverseEngineerObjectResponse response3 = reverseEngineerObject.generateCode( joto,
                                                                                            Collections.EMPTY_LIST );
        printAResponse( response3, "JotoAutoGenerated" );

    }

    private void printAResponse( ReverseEngineerObjectResponse response, String autogeneratedClassName )
        throws IOException
    {
        System.out.println( response );
        String packageFolder = "com/google/code/joto/autogenerated";
        File parentFolder = new File( "src/test/java/" + packageFolder + "/" );
        parentFolder.mkdirs();
        File autogeneratedClassFile = new File( parentFolder, autogeneratedClassName + ".java" );
        PrintStream out = new PrintStream( autogeneratedClassFile );
        out.println( "package " + packageFolder.replace( "/", "." ) + ";" );
        out.println( response.imports );
        out.println( "/** " );
        out.println( " * This class was automatically generated and it is present on the svn " );
        out.println( " * only as an example documentation." );
        out.println( " */" );
        out.println( "class " + autogeneratedClassName + " {" );
        out.println( "  public static void main(String [] args) {" );
        out.println( "    System.out.println(\"Created instance: \");" );
        out.println( "    System.out.println(" );
        out.println( response.code );
        out.println( "    );" );
        out.println( "  }" );
        out.println( "}" );
        System.out.println( "autogeneratedClassFile: " + autogeneratedClassFile.getAbsolutePath() );
    }

}
