package com.google.code.joto.autogenerated;
import java.util.Map;
import java.util.Collection;
import com.google.code.joto.Joto;
import java.lang.String;
import com.google.code.joto.exportable.Creator;
import java.util.Set;
import java.util.List;
import static com.google.code.joto.exportable.ReverseEngineerReflectionUtil.*;

/** 
 * This class was automatically generated and it is present on the svn 
 * only as an example documentation.
 */
class JotoAutoGenerated {
  public static void main(String [] args) {
    System.out.println("Created instance: ");
    System.out.println(
new Creator<Joto>(){ 
public Joto create() {
Joto obj = new Joto(  );
registerInstance( 32635808, obj);  /* @1f1fba0 */
obj.setName("j-oto");
obj.setVersion("1.0");
return obj;
}}.create()
    );
  }
}
