package com.google.code.joto.autogenerated;
import com.google.code.joto.exportable.InstancesMap;
import java.util.Map;
import com.google.code.joto.exportable.Creator;
import java.lang.String;
import java.util.Set;
import java.util.List;
import java.util.ArrayList;
import java.util.Collection;
import static com.google.code.joto.exportable.ReverseEngineerReflectionUtil.*;

/** 
 * This class was automatically generated and it is present on the svn 
 * only as an example documentation.
 */
class SomeStringsSandbox {
  public static void main(String [] args) {
    System.out.println("Created instance: ");
    System.out.println(
new Creator<ArrayList>(){ 
public ArrayList create() {
final InstancesMap instancesMap = new InstancesMap();
ArrayList generatedObject = new Creator<ArrayList>(){ 
public ArrayList create() {
ArrayList col = new ArrayList(  );
col.add("some");
col.add("234");
return col;
}}.create();
return generatedObject;
}}.create()
    );
  }
}
